version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - temploy
  web:
    container_name: temploy-backend
    build: ./
    volumes:
      - ./:/var/www/
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "nginx-proxy"
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_PORT=8000
      - PYTHONUNBUFFERED=0
      - VIRTUAL_HOST=temploy-back.localhost
    networks:
      - temploy

networks:
    temploy:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
