# Generated by Django 2.0.3 on 2018-04-03 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temploybackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_phone',
            field=models.CharField(max_length=10),
        ),
    ]
