# Generated by Django 2.0.4 on 2018-04-23 16:28

from django.db import models, migrations

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'Moderators'),
    ])


def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[
            u'Moderators',
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('temploybackend', '0002_application'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
