# Generated by Django 2.0.4 on 2018-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temploybackend', '0004_application_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
